
CREATE TABLE public."Tariff_Database" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  service_provider text,
  tariff_name text,
  country text,
  pricing_type text,
  electricity_price numeric,
  currency text
);

ALTER TABLE public."Tariff_Database" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to tariffs"
  ON public."Tariff_Database"
  FOR SELECT
  TO public
  USING (true);
